services:
    pim_catalog.job.job_parameters.default_values_provider.variant_group_xlsx_import:
        class: '%akeneo_batch.job.job_parameters.empty_values_provider.class%'
        arguments:
            -
                - '%pim_catalog.compute_product_models_descendants_completeness.job_name%'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }
