parameters:
    pim_catalog.job.job_parameters.constraint_collection_provider.compute_product_models_descendants_completeness.class: Pim\Component\Catalog\Job\JobParameters\ConstraintCollectionProvider\ComputeProductModelsDescendantsCompleteness

services:
    pim_catalog.job.job_parameters.constraint_collection_provider.compute_product_models_descendants_completeness:
        class: '%pim_catalog.job.job_parameters.constraint_collection_provider.compute_product_models_descendants_completeness.class%'
        arguments:
            - ['compute_product_models_descendants_completeness']
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }
